import { useEffect, useState } from 'react';
import { executeDatabaseLogin, validateSignupForm } from '../lib/validation.mjs';
import { supabase, supabaseConfigMissing } from './lib/supabaseClient';

const roles = ['customer', 'vendor', 'driver', 'rider'];
const products = ['Premium roofing sheets', 'Utility knife set', 'Solar power station 600W', 'USB-C fast charge kit'];
const pageForPath = path => path === '/login' ? 'login' : path === '/signup' ? 'signup' : path.includes('vendor') ? 'inventory' : path.includes('rider') || path.includes('driver') ? 'dispatch' : path.includes('wallet') ? 'wallet' : path.includes('profile') ? 'profile' : 'dashboard';

function App(){
  const [page, setPage] = useState(() => pageForPath(location.pathname));
  const [user, setUser] = useState(null);
  const [role, setRole] = useState('customer');
  const navigate = next => { const path = next === 'login' ? '/login' : next === 'signup' ? '/signup' : `/dashboard/${next === 'inventory' ? 'vendor' : next}`; history.pushState({}, '', path); setPage(next); };
  useEffect(() => { const onPop = () => setPage(pageForPath(location.pathname)); window.addEventListener('popstate', onPop); supabase.auth.getSession().then(({data}) => { if(data.session){ setUser(data.session.user); setRole(data.session.user.user_metadata?.role || 'customer'); } }); return () => window.removeEventListener('popstate', onPop); }, []);
  if(page === 'login') return <Auth mode="login" onNavigate={navigate} onSuccess={(nextUser, nextRole) => { setUser(nextUser); setRole(nextRole); navigate('dashboard'); }} />;
  if(page === 'signup') return <Auth mode="signup" onNavigate={navigate} onSuccess={(nextUser, nextRole) => { setUser(nextUser); setRole(nextRole); navigate('dashboard'); }} />;
  if(!user) return <Auth mode="login" onNavigate={navigate} onSuccess={(nextUser, nextRole) => { setUser(nextUser); setRole(nextRole); navigate('dashboard'); }} />;
  return <Workspace page={page} role={role} user={user} onNavigate={navigate} onLogout={async () => { await supabase.auth.signOut(); setUser(null); navigate('login'); }} />;
}

function Auth({ mode, onNavigate, onSuccess }){
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [selectedRole, setSelectedRole] = useState('customer'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async event => { event.preventDefault(); setError(''); const validation = mode === 'signup' ? validateSignupForm({fullName:name, email, password}) : null; if(validation && !validation.isValid){ setError(Object.values(validation.errors)[0]); return; } if(mode === 'login' && (!email.trim() || !password)){ setError('Enter your email address and password.'); return; } setBusy(true); try { if(mode === 'login'){ const result = await executeDatabaseLogin(supabase, email, password); if(!result.success) throw new Error(result.error); onSuccess(result.user, result.role); } else { const {data,error: authError} = await supabase.auth.signUp({email:email.trim(), password, options:{data:{full_name:name.trim(), role:selectedRole}}}); if(authError) throw authError; if(!data.session){ setError('Check your email to confirm your account before signing in.'); return; } onSuccess(data.user, selectedRole); } } catch(errorValue){ setError(errorValue.message || 'Authentication failed.'); } finally { setBusy(false); } };
  return <main className="auth-page"><section className="auth-card"><span className="eyebrow">BRUKINA ACCESS</span><h1>{mode === 'login' ? 'Welcome back' : 'Create your workspace'}</h1><p>{mode === 'login' ? 'Sign in to resume managing your marketplace workspace.' : 'Choose how you participate in the marketplace.'}</p>{error && <div className="error">{error}</div>}{mode === 'signup' && <div className="role-grid">{roles.map(item => <button className={selectedRole === item ? 'role selected' : 'role'} type="button" key={item} onClick={() => setSelectedRole(item)}>{item}<small>{item === 'customer' ? 'Shop and track' : item === 'vendor' ? 'Sell inventory' : 'Move orders'}</small></button>)}</div>}<form onSubmit={submit}>{mode === 'signup' && <label>Full name<input value={name} onChange={event => setName(event.target.value)} required /></label>}<label>Email address<input type="email" value={email} onChange={event => setEmail(event.target.value)} required /></label><label>Password<input type="password" value={password} onChange={event => setPassword(event.target.value)} required /></label><button className="primary" disabled={busy}>{busy ? 'Connecting...' : mode === 'login' ? 'Sign in to workspace' : 'Create account'} <span>→</span></button></form><button className="link" onClick={() => onNavigate(mode === 'login' ? 'signup' : 'login')}>{mode === 'login' ? 'Create account' : 'Already have an account? Sign in'} ↗</button></section></main>;
}

function Workspace({page, role, user, onNavigate, onLogout}){ const title = page === 'inventory' ? 'Catalog management' : page === 'dispatch' ? 'Dispatch center' : page === 'wallet' ? 'My wallet' : page === 'profile' ? 'Your profile' : 'Marketplace dashboard'; return <div className="shell"><header><a className="brand" onClick={() => onNavigate('dashboard')}>brukina<span>.</span></a><button className="link" onClick={onLogout}>Sign out</button></header><div className="layout"><aside><b>{role} workspace</b><button onClick={() => onNavigate('dashboard')}>Dashboard</button><button onClick={() => onNavigate('profile')}>Profile</button><button onClick={() => onNavigate('inventory')}>Inventory</button><button onClick={() => onNavigate('orders')}>Orders</button><button onClick={() => onNavigate('dispatch')}>Dispatch</button><button onClick={() => onNavigate('wallet')}>Wallet</button></aside><main className="content"><span className="eyebrow">{role.toUpperCase()} WORKSPACE</span><h1>{title}</h1><p>Welcome back, {user.user_metadata?.full_name || user.email}.</p>{page === 'dashboard' && <div className="product-grid">{products.map(product => <article className="product" key={product}><span>TRADE PRICE</span><h2>{product}</h2><button className="primary">Buy now →</button></article>)}</div>}{page === 'inventory' && <Panel title="Vendor inventory">Add and manage marketplace products from this workspace.</Panel>}{page === 'dispatch' && <Panel title="Active manifest">No delivery requests are assigned yet.</Panel>}{page === 'wallet' && <Panel title="Secure wallet">Your balance and settlement activity will appear here.</Panel>}{page === 'profile' && <Panel title="Account profile">{user.email} · {role}</Panel>}{page === 'orders' && <Panel title="Order history">No orders yet. Browse the marketplace to get started.</Panel>}</main></div></div>; }
function Panel({title, children}){ return <section className="panel"><h2>{title}</h2><p>{children}</p></section>; }
export default App;
